#!/bin/bash

set -e

command="$1"

data_branch="${CI_STORAGE_DATA_BRANCH:-ci/persistent-storage}"
remote_url="$(git config --get remote.origin.url)"

# CI_STORAGE_REPO_ROOT gets set before the script is called via one of the provided github actions
# you can also manually set it if you run a custom setup, where the script is not located in then
# root of the repository
if [[ "$CI_STORAGE_REPO_ROOT" ]]
then
    root_dir="$CI_STORAGE_REPO_ROOT"
else
    # if the repo root wasn't set, we base it off the script location
    script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
    pushd "$script_dir" &>/dev/null || exit 1
    root_dir="$(git rev-parse --show-toplevel)"
    popd &>/dev/null || exit 1
fi

pushd "$root_dir" &>/dev/null || exit 1

err() { printf "%s\n" "$*" >&2; }

config_github() {
    git config --global user.name "CI Storage"
    git config --global user.email "$GITHUB_REPOSITORY_OWNER@users.noreply.github.com"
}

configure_git () {
    if [[ "$CI_STORAGE_GIT_CONFIG" == "skip" ]]
    then
        return 0
    elif [[ "$CI_STORAGE_GIT_CONFIG" ]]
    then
        if [ ! -f "$CI_STORAGE_GIT_CONFIG" ]; then
            err "CI_STORAGE_GIT_CONFIG is set, but it neither contains the value 'skip' nor a valid path to a script" \
                "to configure git."
            exit 1
        fi
        if [[ ! -x "$CI_STORAGE_GIT_CONFIG" ]]
        then
            err "CI_STORAGE_GIT_CONFIG is set, but the script at the given path is not executable."
            exit 1
        fi
        bash -c "$CI_STORAGE_GIT_CONFIG"
    elif [[ "$GITHUB_ACTIONS" == "true" ]]
    then
        config_github
    else
        err "CI environment not supported yet!"
        err "If you know how to detect your CI environment and how to configure git to allow pushing from CI," \
            "feel free to submit an issue with the information needed to add the CI environment or" \
            "create a PR to add support yourself."
        exit 1
    fi
}

init_ci_storage () {
      # do this first so we exit early when we can't configure git properly
      configure_git || exit 1

      # create the branch for storing the data and check it out
      git checkout -b "$data_branch"

      # if the branch didn't exist, make sure it's empty
      # this is because the files in here are for storing data across CI runs
      # and not for the actual codebase
      git rm -rf ./*
      git rm -rf .github
      git rm .gitignore

      # create the expected directory structure
      # and add .gitkeep, so that git doesn't complain about empty directories
      mkdir -p .ci-storage
      touch .ci-storage/.gitkeep

      # add changes to git, commit and push
      git add .ci-storage
      git commit -m "initialize ci-storage"
      git push origin "$data_branch"

      # switch back to the previous branch
      git checkout -
}

shopt -s nocasematch
case "$command" in
  path)
      echo "$(pwd)"/.ci-storage
      ;;


  init)
      init_ci_storage || exit 1
      ;;

  get)
     echo "Setting up .ci-storage for $remote_url"
     git pull

     git ls-remote --exit-code origin "$data_branch" >/dev/null 2>&1
     exit_code=$?

      if [ ${exit_code} -ne 0 ]
      then
          if [[ "$CI_STORAGE_INIT" == "no_auto" ]]
          then
              err "CI_STORAGE_INIT is set to 'no_auto'. Please run './ci-storage init' manually before calling" \
                  "ci-storage get or persist."
              exit 1
          fi
          init_ci_storage || exit 1
      fi
      git checkout origin/"$data_branch" -- .ci-storage
    ;;

  persist)
      configure_git || exit 1

      git checkout "$data_branch"

      git pull --ff-only
      git add .ci-storage
      git commit -m "update"
      git push origin "$data_branch"
    ;;

  *)
    echo "Invalid command"
    exit 1
    ;;
esac

popd &>/dev/null || exit 1 # git root